config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, numericality: { only_integer: true }
  validates :number_of_guests, numericality: { only_integer: true, in: 1..10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'json'

class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
    if params[:search_flat] != ' '
      @flats = @flats.where('name like ?', "%#{params[:search_flat]}%")
    else
      @flats
    end
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit;
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container-edit-form">
<h2>Add your flat:</h2>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.input :image %>
    <%= f.submit %>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All our Flats</h1>
  <p>All <%= @flats.count %> flats.</p>
  <div class="card-container d-flex flex-wrap rounded">
    <% @flats.each do |flat| %>
      <div class=" m-1" style="width: 24rem;">
        <div class="card-main card-body">
        <%= link_to flat_path(flat) do %>
          <img class="card-img-top" src="<%= flat.image %>" heigth="150px" width="" alt="Card image cap">
        <% end %>
          <div class="card-bottom-container">
            <div class="text-container ">
              <p class="card-title"><%= flat.name %></p>
              <p class="card-address"><%= flat.address %></p>
              <p class="card-text"><span>🏷 <strong>€ <%= flat.price_per_night %></strong></span> <span>👫 <strong><%= flat.number_of_guests %></strong></span></p>
            </div>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
<h2>Add your flat:</h2>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit %>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="hero-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url(<%= @flat.image %>)">

</div>
<div class="d-flex justify-content-center">
  <div class="container-show">
    <div class="container-main">
      <div class="container-title grey-card ">
        <h2><%= @flat.name %></h2>
        <p><%= @flat.address %></p>
      </div>

      <div class="container-title grey-card ">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>

    <div class="container-left-sidebar container-main">
      <div class="container-details grey-card ">
      <H3>Details:</H3>
      <p>🧙🏻‍♀️ Guests: <%= @flat.number_of_guests %> </p>
      <p>💴 Price per night: €<%= @flat.price_per_night %></p>
      </div>

      <div class="container-social d-flex justify-content-between align-items-center grey-card">
      <p>Share</p>
      <div class="social-container">
              <%= link_to 'Edit', edit_flat_path(@flat), class: "card-link text-warning" %>
              <%= link_to 'Remove', flat_path(@flat), method: :delete, data: { confirm: "Are you sure?" }, class: "card-link text-danger" %>
            </div>
      </div>
      <div><%= @map %></div>
    </div>
<div>
<div class="map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=10 Clifton Gardens London W9 1DT&amp;zoom=13&amp;scale=2&amp;size=1000x1000&amp;maptype=roadmap&amp;markers=color:red%7C10 Clifton Gardens London W9 1DT&amp;key=AIzaSyAPpx0wk4d-AQ8bhe8-a-ihC7NXLoPElhg')"></div>
</div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to '🏡💕 Liarbnb', flats_path, class: 'navbar-logo' %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ms-auto d-flex">
          <%= form_tag "/flats", method: "GET", class: "d-flex my-2 my-lg-0" do %>
           <%= text_field_tag :search_flat, params[:search_flat], class: "form-control mx-2", placehodler: 'Search..'  %>
            <%= submit_tag "Search", class: "btn btn-red mx-2 rounded" %>
          <% end %>
          <%= link_to "Add flat", new_flat_path, class: "btn btn-white my-2 my-sm-0 ms-2" %>
        </div>
      </div>
      </div>
    </nav>


    <%= yield %>
  </body>
</html>